env:
  - DOCKER_USERNAME=fengzhanyuan
sudo: required
language: python
services:
  - docker
python:
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install -y sshpass
  - docker info
  - docker ps -a
install:
  - pip install -r requirements.txt
script:
  - pytest -v tests.py
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker version
  - pwd
  - docker build -t lyrewing/skyline-admin:1.0 .
  - docker push lyrewing/skyline-admin:1.0
  - docker images
  - sshpass -p "$SSH_PASSWORD" ssh dc2-user@116.85.24.98
  - ls -a
  
