env:
  - DOCKER_USERNAME=fengzhanyuan
sudo: required
language: python
services:
  - docker
python:
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install -y sshpass
  - docker info
  - docker ps -a
install:
  - pip install -r requirements.txt
script:
  - pytest -v tests.py
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker version
  - pwd
  - docker build -t lyrewing/skyline-admin:1.0 .
  - docker push lyrewing/skyline-admin:1.0
  - docker images
  - sshpass -p "$SSH_D" ssh dc2-user@$HOST
  - sudo docker rmi -f lyrewing/skyline-admin:1.0
  - sudo docker pull lyrewing/skyline-admin:1.0
  - sudo docker run -d -p 80:5000 --name=admin_web -e MYSQL_HOST=admin_db -e MYSQL_PORT=3306 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DB=admin --network=admin_bridge lyrewing/skyline-admin:1.0
  
