version: '2'
services:
  web:
      image: 'lyrewing/skyline-admin:1.0'
      ports:
        - 80:5000
      environment:
        - MYSQL_HOST=db
        - MYSQL_PORT=3306
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DB=admin
      networks:
        - n_bridge
      depends_on:
        - db
      privileged: true
      cpu_shares: 30
      mem_limit: 100m
      memswap_limit: 100m
  db:
      image: 'mysql:5.7'
      ports:
        - 33062:3306
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=admin
      volumes:
        - v_db:/var/lib/mysql
      networks:
        - n_bridge
      privileged: true
      cpu_shares: 30
      mem_limit: 200m
      memswap_limit: 200m
volumes:
  v_db:
networks:
  n_bridge:
    driver: bridge
